/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

############
# GRAPHICS #
############
/vis/open OGLIX
/vis/viewer/set/background white
/vis/drawVolume

#######################
# ADDITIONAL SETTINGS #
#######################
/vis/viewer/set/viewpointVector 0 -1 0
/vis/viewer/set/upVector 0 0 0
/vis/viewer/set/upVector 0 0 1
#/vis/viewer/set/projection perspective 30 deg
#/vis/viewer/set/style surface
/vis/viewer/zoom 5.0

#/vis/viewer/set/cutawayMode intersection
#/vis/viewer/addCutawayPlane 0 0 0 mm 0 -1 0

############################
# GIVE COLORS TO PARTICLES #
############################
/vis/modeling/trajectories/create/drawByParticleID 
/vis/modeling/trajectories/drawByParticleID-0/set mu+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set mu- magenta
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set neutron green
/vis/modeling/trajectories/drawByParticleID-0/set gamma red

###############################
# SHOW AND STORE TRAJECTORIES #
###############################
/tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 100
/vis/scene/endOfRunAction accumulate 
/vis/viewer/set/hiddenMarker 1

#######################
# FILTER TRAJECTORIES #
#######################
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/add mu+


#######
# RUN #
#######

/xe/gun/type Point
/xe/gun/angtype iso
/xe/gun/center 129.0 0.0 -20.0 mm

/xe/gun/energy 0 keV
/xe/gun/particle ion
/xe/gun/ion 27 57 0 0


/run/beamOn 100
