/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

############
# GRAPHICS #
############
/vis/open OGLIX
/vis/drawVolume

#/vis/viewer/set/viewpointVector 0 1 0
#/vis/viewer/set/upVector 0 0 0
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/set/projection perspective 1 deg
#/vis/viewer/set/style surface
#/vis/viewer/zoom 0.5

#/vis/viewer/set/cutawayMode intersection
#/vis/viewer/addCutawayPlane 0 0 0 mm 0 -1 0

############################
# GIVE COLORS TO PARTICLES #
############################
/vis/modeling/trajectories/create/drawByParticleID 
/vis/modeling/trajectories/drawByParticleID-0/set mu+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set mu- magenta
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set neutron green
/vis/modeling/trajectories/drawByParticleID-0/set gamma red

###############################
# SHOW AND STORE TRAJECTORIES #
###############################
/tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 100
#/vis/scene/endOfRunAction accumulate 
/vis/viewer/set/hiddenMarker 1

#######################
# FILTER TRAJECTORIES #
#######################
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/add mu+


#######
# RUN #
#######
/xe/gun/type Volume
/xe/gun/shape Sphere
/xe/gun/radius 0.5 mm

/xe/gun/center 0.0 328.0 1015.0 mm

/xe/gun/angtype direction
/xe/gun/direction 0 -1 0

# Cs-137
#/xe/gun/energy 0 keV
#/xe/gun/particle ion
#/xe/gun/ion 55 137 0 0

#monoenergetic gamma
/xe/gun/energy 662 keV
/xe/gun/particle gamma

#collimator position
#| > X:                   0 mm
#| > Y:                   328 mm
#| > Z:                   1015 mm

/run/beamOn 100






