/control/verbose 2
/run/verbose 2
/event/verbose 2
/tracking/verbose 2


/xe/gun/particle geantino

/xe/gun/angtype direction

#collimator center
#/xe/gun/center 0.0 328.0 1015.0 mm
#/xe/gun/center  0.0 2000.0 1020.0 mm
#/xe/gun/center  0.0 1000.0 1021.0 mm

#LXe center
#/xe/gun/center 0.0 0.0 -1000 mm
/xe/gun/center 00.0 0.0 0.0 mm

#aperture
#/xe/gun/center 0.0 -237.5 3000.0 mm

#beam
#/xe/gun/center 10.0 -3000.0 0.0 mm

/xe/gun/direction 0 0 1

/run/beamOn 1
